### ISSUE TITLE
This plugin is great but Lightning Charge installation and configuration is way to complicated

### ISSUE THREAD

**Issue by InternetofTrust** [ElementsProject/wordpress-lightning-publisher#2]
This plugin is great but Lightning Charge installation and configuration is way to complicated for the average Wordpress admin. 

Could third parties provide Lightning Charge servers and charge a small fee for this service? No one is going to install this if they have to run, secure and maintain a complicated Linux node. 

This plugin is still a huge step forward, history being made.

**Comment by shesek** [comment]
Yes, I agree, setting up Lightning Charge as a separate standalone server is not for the average WordPress user. This does require some tech savviness and sysadmin experience.

Third parties can definitely offer a hosted version of Lightning Charge to make that easier, if you're okay trusting them to hold funds on your behalf. I don't have any plans of offering such services.

Note, however, that the setup isn't really all that complicated. If you're comfortable with command line, have some experience managing servers over SSH and familiar with Docker, getting Lightning Charge to run is basically as simple as writing these two commands:

```bash
$ mkdir data
$ docker run -u `id -u` -v `pwd`/data:/data -p 9112:9112 \
             -e API_TOKEN=mySecretToken \
             shesek/lightning-charge
```

This will setup everything up and start Lightning Charge on port 9112 with `mySecretToken` as the API access token.

The docker image comes bundled with bitcoind+lightningd+lightning-charge, so you don't have to pre-install anything other than Docker itself.

**Comment by shesek** [comment]
@NicolasDorier also made an awesome [one-click azure deployment](https://github.com/NicolasDorier/lightning-charge-azure) solution. An instructional video is [available here](https://www.youtube.com/watch?v=D4RqULSA4uU).

**Comment by NicolasDorier** [comment]
I still need to update it, will do this week. Lightning has issues with LND right now it seems from my users.
