### ISSUE TITLE
Custom "pay" text and button don't show complete sentence.

### ISSUE THREAD

**Issue by reathh** [ElementsProject/wordpress-lightning-publisher#4]
Using the example from your "Usage" section 
`[ifpaid 0.005 ILS text="Please pay to continue reading." button="Alright, I'll pay!"]`

Only the first word in the quotes becomes visible (and also the first quote, which shouldn't be like that):
![2018-07-22_15-26-40](https://user-images.githubusercontent.com/7622630/43045579-bb156f3e-8dc3-11e8-9251-4b8c43e168b5.png)

**Comment by shesek** [comment]
It looks like something is changing your quotes from the regular `"` to a `“`, which are not properly parsed as [wordpress shortcodes](https://codex.wordpress.org/shortcode). Some plugin getting in the way, maybe?

It seems that I've previously ran into it and [added some code](https://github.com/ElementsProject/wordpress-lightning-publisher/blob/f9408fe722c31d784bb422e6d7b5b8685ac2237f/lightning-publisher.php#L126) to manually convert the closing mark (aka `&#8221;`) but not the opening one (aka `&#8220;`).

I updated the shortcode parser to manually convert both of them in 57e240f09423faf3517ef8462f137edd57d6cb49. Can you try and verify it works?

**Comment by reathh** [comment]
#https://github.com/ElementsProject/wordpress-lightning-publisher/commit/57e240f09423faf3517ef8462f137edd57d6cb49 fixed the issue. Thank you!
